### ISSUE TITLE
Re-read JSON data from disk periodically to notice changes

### ISSUE THREAD

**Issue by fwenzel** [mozilla/django-product-details#1]
The JSON files are not re-read from disk as long as the Python process is alive, potentially a long time[TM].

jsocol suggests dropping the dicts into memcached with a somewhat long expiration time, and once memcached drops them, we re-read them from disk.

Though we could also do that by keeping everything the way it is (thread-local) and set an expiration time. When that time comes around, we drop and re-read the JSON data.

**Comment by pmclanahan** [comment]
Fixed in #39.
