### ISSUE TITLE
A way to check for missing files

### ISSUE THREAD

**Issue by jsocol** [mozilla/django-product-details#26]
If I run `update_product_details` and then delete a file, or even all the files (I can delete one file like `languages.json` or I can do `find . -name "*.json" -delete`) except `.last_update`, then `update_product_details` won't download anything without `-f`. Since `.last_update` is designed to be "missed" on filesystems, this is a pretty easy scenario.

If there were another command, or something like a `--check` switch to `update_product_details`, that would cause it to actually verify that the files are on the filesystem, it would be possible to diagnose issues like "one file didn't download, or got deleted, or didn't get synced" and and if there were a secondary option, like `--check --fix`, it would be easy to redownload missing files.

**Comment by pmclanahan** [comment]
Closing for now. Reopen if you need this.
