### ISSUE TITLE
URLError does not always have a code.

### ISSUE THREAD

**Issue by tarekziade** [mozilla/django-product-details#27]
I got a bug where the URLError had no code (the only attribute defined in this class is reason)

so in the code base, like at https://github.com/fwenzel/django-mozilla-product-details/blob/master/product_details/management/commands/update_product_details.py#L141

You should always test if e has a code attribute.

**Comment by Natim** [comment]
I just ran into the same error today: https://github.com/mozilla/addons-server/issues/1952

**Comment by Natim** [comment]
Apparently the problem was fixed with last version of django-product-details compatible with Django > 1.8

**Comment by pmac** [comment]
I'll mark this as done then. Reopen if it's still an issue for anyone.
