### ISSUE TITLE
Add optional DB file data storage backend

### ISSUE THREAD

**Issue by pmclanahan** [mozilla/django-product-details#42]
Doesn't seem very [12 Factor](http://12factor.net/backing-services) to use the filesystem to store and update these data. In order to use this lib on something like Heroku we need to store and update the data in the DB. It'd also make deployment a lot easier for people using containers (e.g. Docker).

**Comment by pmclanahan** [comment]
Actually, I think the right way is to convert JSON file storage to use a Django Storage class and have that storage be configurable. This way people could use the FS, DB, S3, or any other thing they want.

Thoughts?

**Comment by jgmize** [comment]
Using the django storage class makes sense if you want to be able to put the json somewhere like s3, but if using the DB I'd rather see a regular model  than something like https://django-storages.readthedocs.org/en/latest/backends/database.html.

**Comment by pmclanahan** [comment]
I agree that that particular backend is suboptimal. But writing a simple ORM-based db backend would be pretty easy. My primary thought is that the Storage API is a nice standard interface for the library, and offers people the most flexibility for storage, especially since they'll likely have already had to configure a storage class for file uploads. 

Another of my concerns is that I know of other areas of bedrock where we need to deal with external file storage and it would be nice to avoid inventing this wheel multiple times.
