### ISSUE TITLE
ProductDetails.last_update property always return defaultdict(lambda: None)

### ISSUE THREAD

**Issue by diox** [mozilla/django-product-details#49]
In https://github.com/mozilla/django-product-details/commit/b278b8068d102474a92d5742c58bd64a47793faa#diff-28be742a611a61de97e9c341706547ebR58 `ProductDetails.last_update` property was changed to this implementation:

```
    @property
    def last_update(self):
        """Return the last-updated date, if it exists."""
        return self._storage.last_updated('/')
```

The `last_updated` method does not exist on any storage class, so it throws an error, that causes the property to fail and the `__getattr__` method in the class is used instead, and it returns `defaultdict(lambda: None)`. It looks like it wasn't the desired behavior, since that means checking `product_details.last_update` will always return something falsy.

Am I misunderstanding how this works ?

**Comment by pmclanahan** [comment]
0.8.2 was just pushed to PyPI with this fix. Thanks again for the report.
