### ISSUE TITLE
Use the new product-details powered by Ship-It

### ISSUE THREAD

**Issue by kyoshino** [mozilla/django-product-details#51]
We should use https://product-details.mozilla.org/ instead of https://svn.mozilla.org/libs/product-details/json/.

**Comment by pmclanahan** [comment]
We should indeed. I've not yet gotten word from Sylvestre that it's ready for prod yet however. Last I checked the versions in the files in product-details.m.o were not yet up-to-date.

**Comment by sylvestre** [comment]
Confirmed, this is not ready yet (but very soon)

**Comment by sylvestre** [comment]
This is ready to be used!

**Comment by pmac** [comment]
Done as of 4481a30a51deff1ad39afe135c83c1021f290ad5.
