### ISSUE TITLE
0.8.2 initial migration fail

### ISSUE THREAD

**Issue by chrmod** [mozilla/django-product-details#59]
While setting up addons-server from scratch, django-product-details migration fail. See linked issue: https://github.com/mozilla/addons-server/issues/2568

It is exactly this line causing the problem:
https://github.com/mozilla/django-product-details/blob/63c58051842835d1f21c554ba1367c1e55ef2a8a/product_details/storage.py#L234

More specifically:
storage.last_modified('regions/') returns None instead of time string

**Comment by pmac** [comment]
Have you tried a newer version? Latest is 0.11.1.

**Comment by chrmod** [comment]
cannot use it with latest addon-server as it requires different version of django

**Comment by pmac** [comment]
Not sure what the deal is. I do have a branch that backports the latest
version for Django 1.7. We didn't release it since 1.7 is no longer
supported. But you can use the branch if you want. Look at the requirements
in the bedrock project.

- pmac mobile

**Comment by pmac** [comment]
Here's a link to the [requirement in bedrock](https://github.com/mozilla/bedrock/blob/master/requirements/base.txt#L88-L89).

**Comment by EnTeQuAk** [comment]
We upgraded addons-server to use the most recent version so this is now "fixed" and can be closed.

**Comment by pmac** [comment]
Thanks for the followup.
