### ISSUE TITLE
README might need a refresh

### ISSUE THREAD

**Issue by stevejalim** [mozilla/django-product-details#86]
While debugging an issue with release data I tried to find and browse the SVN repo mentioned in the README.

It doesn't appear to exist, but the README implies it does and that it's still used. I _think_ instead the data now comes from https://github.com/mozilla-releng/product-details but we should check this and update the docs accordingly

**Comment by stevejalim** [comment]
@pmac What's your 2c on this - is the SVN repo long gone?

**Comment by pmac** [comment]
The data by default comes from https://product-details.mozilla.org/1.0/ (see [settings defaults](https://github.com/mozilla/django-product-details/blob/master/product_details/settings_defaults.py#L7)), the management command scrapes that site and downloads all of the files. In bedrock we don't have it do that and we manually fetch the git repo you mentioned and load the data using this library.

**Comment by janbrasna** [comment]
@stevejalim This happened in #51 for [v0.12](https://github.com/mozilla/django-product-details/releases/tag/0.12) — bug details: https://bugzil.la/1282494

Let me know if there's someone with _write_ role interested in a PR updating the readme info, I can take a look at it for sure 🧹

**Comment by stevejalim** [comment]
@janbrasna if you are happy to submit a PR for a README change am sure we can get it reviewed and merged
